version: '3.2'
services:
  app:
    container_name: app_valorys
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./app
        target: /app
        excludes:
          - /app/node_modules
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./db:/dta/db
    ports:
      - "27017:27017"