version: "2"
services:
  app:
    container_name: app_valorys
    restart: always
    build: .
    ports:
      - "80:80"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./db:/dta/db
    ports:
      - "27017:27017"